/**
 * Seed the Supabase database with constitution articles and EXCO members.
 * Run: cd backend && node ../database/seed.js
 */
const path = require('path');
const backendModules = path.join(__dirname, '..', 'backend', 'node_modules');
require(path.join(backendModules, 'dotenv')).config({ path: path.join(__dirname, '..', 'backend', '.env') });
const { createClient } = require(path.join(backendModules, '@supabase', 'supabase-js'));

const s = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const constitutionArticles = [
  { article_number: 0, title: 'PREAMBLE', content: `We, the former students of St Teresa's College Nsukka (1992 -1998) in order to strengthen the ties between us and our alma mater, St Teresa's College Nsukka, and also seek ways of giving back to our alma mater, creating opportunities for group and individual advancement, do hereby form for ourselves this constitution.` },
  { article_number: 0, title: 'SCHEDULE 1 - OATH OF OFFICE FOR OFFICIALS', content: `I …………………… being elected as …………………. of STOBA 98 do solemnly swear/affirm that I will discharge my duties creditably to the best of my ability, faithfully and in accordance with the constitution of STOBA 98, and always in the best interest of solidarity, integrity, well-being and prosperity of STOBA 98. I will strive to preserve the fundamental objectives and principles of STOBA 98 as contained in the constitution of STOBA 98. I will not allow my personal interest to influence my official conduct or my official decisions. I will do right to all members according to the constitution of STOBA 98 without fear or favour, affection or ill will; and I will do my best to preserve, protect and defend the constitution of STOBA 98.\n\nSo help me God.` },
  { article_number: 1, title: 'ARTICLE I - NAME', content: 'The name of this group shall be called, STOBA 98.' },
  { article_number: 2, title: 'ARTICLE II - PURPOSE', content: `The general purpose of this group shall be; to promote the general welfare and cooperation of members, promote the effectiveness of Saint Teresa's College Nsukka, through strengthening the ties between former students of Saint Teresa's College (1992 - 1998) and the College. Stimulate the interest and activity of the alumni of Saint Teresa's College and participate in further development of Saint Teresa's College, Nsukka.` },
  { article_number: 3, title: 'ARTICLE III - MEMBERSHIP', content: `SECTION 1. Regular membership of this group shall be open to all graduates of Saint Teresa's College 1998 and all other former students who passed through the college between 1992 - 1998 but did not graduate from the college.\n\nSECTION 2. Honorary members of this Group shall be those persons who have interest in the welfare of Saint Teresa's College and desire to associate themselves in the activities of this group, and admitted as such, upon approval of the executives. However, the rights of honorary members shall exclude the right to vote or hold office as a member of the group.` },
  { article_number: 4, title: 'ARTICLE IV - OFFICERS', content: `SECTION 1. The officers of this group shall be: President, Vice President, Executive Secretary, Treasurer and Public Relations Officer.\n\nSECTION 2. Duties of Officers.\n\nA. PRESIDENT: The President of this group shall be its chief executive. The President shall preside at all meetings of the group, and at meetings of the Executives/ Executive committee. The President shall represent the group in and at all functions and activities required by his office. The President, with the advice and consent of the Executives, shall appoint all committees of the group and all State Coordinators.\n\nB. VICE PRESIDENT: The Vice President shall be an assistant to the President and in the absence of the President, shall exercise the powers of the President, and shall serve on the Executive Committee.\n\nC. EXECUTIVE SECRETARY: The elected secretary shall serve as the Executive Secretary of the Association, and shall as well serve on the Executive Committee. The duties of the Executive Secretary are to:\n(i) be chief assistant to the group;\n(ii) keep minutes of all meetings;\n(iii) be the chief financial officer of the Group;\n(iv) manage the affairs and daily operations of the Group;\n(v) prepare annual report of the group at the end of every year which will be distributed to all members.\n\nD. THE PUBLIC RELATIONS OFFICER (PRO): The duties of the Public Relations Officer are:\n(i) to publicize the notices of all meetings of the group.\n(ii) to disseminate all approved messages and distribute all circulars and other information of the group.\n\nE. TREASURER:\n(i) It shall be the duty of the treasurer to receive all monies from the Executive Secretary for the use of the group, issue receipts to cover such monies and pay same into the group's bank account within forty-eight (48) hours of receipt of same.\n(ii) He shall keep an accurate account of all monies received and paid by him on behalf of the group.\n(iii) He shall pay no money without an order/payment voucher signed by the President.\n(iv) He shall render a report of his receipt and disbursements at each executive meeting.\n\nSECTION 3. The office of all the executives shall be two-year tenure. Officers will not be eligible to serve in the same position for more than two consecutive terms.` },
  { article_number: 5, title: 'ARTICLE V - BOARD OF DIRECTORS', content: `SECTION 1. The management of this group shall vest on the Board of Directors, consisting of the executives of the group and state coordinators.\n\nSECTION 2. The Board of Directors will meet at least two times each year, at a time and place communicated to its members with at least one-month notification.\n\nSECTION 3. A simple majority of the whole number of board members shall constitute a quorum, and a majority of the votes cast at a regularly convened meeting shall be sufficient to approve all matters of business.\n\nSECTION 4. A board member, who fails to uphold the standards of Saint Teresa's College and STOBA 98 Group, shall lose his membership on the Board by a two-third vote of those present and voting thereon.\n\nSECTION 5. The general meeting which shall hold at least once every year shall be the highest decision making body of the group and all major decisions shall be made through a vote in which a simple majority shall prevail.` },
  { article_number: 6, title: 'ARTICLE VI - ELECTION', content: `SECTION 1. Election of the members of the Executives shall hold every two years.\n\nSECTION 2. Electoral Committee shall be set up to handle election matters. STOBA 98 members present shall nominate members of such committee on the Election Day. A chairperson who will emerge by a simple majority of the appointed electoral committee members shall head the committee. It will be the duty of the electoral committee to conduct the election in a way deemed fit by them and accepted by all members present.` },
  { article_number: 7, title: 'ARTICLE VII - MEETINGS', content: `SECTION 1. A general meeting shall hold at least once every year at a venue, which shall be communicated to all members at least one month before the day, or at such other time as the Board of Directors may determine.\n\nSECTION 2. At least thirty percent (30%) of registered members of the group including at least one executive shall form a quorum, and a majority of the votes cast at a regularly convened meeting shall be sufficient to approve all matters of business.\n\nSECTION 3. The following shall be the usual order of business at regular meetings of the group, but the order may be suspended or changed at any time by the vote of a majority of the members present:\n(i) Prayer;\n(ii) Roll Call;\n(iii) Action on Minutes of Previous Meeting;\n(iv) Reports of Officers of the Association;\n(v) Reports of Special Committees;\n(vi) Unfinished Business;\n(vii) New Business;\n(viii) Any Other Business;\n(ix) Closing Prayer and Adjournment\n\nSECTION 4. Different states/quarters shall hold monthly or quarterly meeting of STOBA 98 at a venue, which shall be communicated to all members in that region at least two weeks before the day. Such meetings shall be presided over by the state coordinator in charge of that region and the minutes of the meetings submitted to the President through the Executive Secretary for proper documentation.` },
  { article_number: 8, title: 'ARTICLE VIII - COMMITTEES', content: `SECTION 1. The President of the Group shall appoint Committees, subject to the approval of the Executives.\n\nSECTION 2. Standing committees shall include:\n(i) Special Events Committee. The Special Events Committee shall be responsible for planning the annual general meeting and other events as needed. The President shall appoint at least three Board members to serve on this Committee.\n\nSECTION 3. Special and ad hoc committees shall be appointed by the President and approved by the Board members when the need arises.` },
  { article_number: 9, title: 'ARTICLE IX - FINANCE', content: `The group shall derive her funds through but not limited to the following ways;\ni. Monthly dues\nii. Voluntary donations made by members and non members\niii. Fund raising activities such as launching and freewill donations\niv. Fines\nv. Any profit-making venture that the group may get involved in` },
  { article_number: 10, title: 'ARTICLE X - ADMINISTRATION OF FUND', content: `The administration of the group's fund shall be guided by the following principles:\ni. The group shall open an account with a recognized bank.\nii. All monies collected for and on behalf of the group shall be deposited in the bank account.\niii. Signatories to the bank account shall be any two of the president, the executive secretary and the treasurer.\niv. All withdrawals must get approval from the president.` },
  { article_number: 11, title: 'ARTICLE XI - DISCIPLINE', content: `The following disciplinary actions shall be taken for any of the following offenses.\ni. Any member who is late for any of our official gatherings without prior notice communicated to and approved by the executives shall pay a fine of five hundred naira (N500) only.\nii. Failure to attend any of our meetings without cogent and verifiable reason communicated to the executives shall attract a fine of one thousand naira (N1,000) only.\niii. Any member who is found in any disgraceful act which is not worthy of a product of St Teresa's College shall stand suspended until after investigation which will be conducted by board of directors and also after the offender has been given opportunity for fair hearing. The board of directors shall have the power to suspend or terminate such a person's membership after fair hearing. However, the person involved can appeal the outcome of the investigation to the general house. If after hearing the investigation report of the board of directors as well as the concerned person's side of the story, the general house, through a simple majority vote, finds the person guilty, his membership will be terminated.` },
  { article_number: 12, title: 'ARTICLE XII - RESIGNATION AND IMPEACHMENT OF OFFICERS', content: `SECTION 1. RESIGNATION OF OFFICERS\nAn officer of the group can at any time resign his position if for cogent verifiable reasons he is no longer able to perform his functions as spelt out in the constitution. Such resignation can only take effect when approved by the board of directors.\n\nSECTION 2. IMPEACHMENT OF OFFICERS\n\nA. GROUNDS FOR IMPEACHMENT\nAn officer of the group can be impeached on any of the following grounds.\ni. Financial misappropriation.\nii. Gross misconduct and negligence of duty as an executive member.\niii. Insubordination.\n\nB. IMPEACHMENT PROCESS\ni. The impeachment process shall begin by an impeachment motion moved by a registered member of the group.\nii. The motion shall be seconded by another registered member.\niii. This shall be proceeded by deliberation and hearing from all the involved parties.\niv. After due hearing and deliberations, the concerned officer shall stand impeached upon a two-third vote of members present at meeting on the impeachment motion.\n\nC. Any impeached officer automatically ceases to be a member of the board of directors and will not be eligible to occupy any office in the group after such impeachment.` },
  { article_number: 13, title: 'ARTICLE XIII - FILLING OF VACANCIES', content: `In case of any vacancy that may arise before the end of the tenure of elected officials, the board of directors shall have the power to fill such vacancies. However, if thirty percent (30%) of registered members indicate their rejection of the appointed officer, an election shall be held to fill the vacancy during the annual general meeting provided that an announcement is made to that effect at least one month before the day of the meeting.` },
  { article_number: 14, title: 'ARTICLE XIV - AMENDMENTS', content: `This Constitution and By-laws shall be subject to amendment at any annual general meeting of the group by a two-thirds vote of those present and voting thereon, provided that the proposed amendment or amendments have been submitted in writing to the Board of Directors and a notice of the proposed amendment given to members before the day of the meeting.` },
];

const excoMembers = [
  { name: 'Admin User', position: 'President', contact: '+234 801 000 0001', is_active: true },
  { name: 'Exco Member', position: 'Vice President', contact: '+234 802 000 0002', is_active: true },
  { name: 'Kunle Adeyemi', position: 'Executive Secretary', contact: '+234 806 000 0006', is_active: true },
  { name: 'Chidi Nnamdi', position: 'Treasurer', contact: '+234 807 000 0007', is_active: true },
  { name: 'Femi Ogunlana', position: 'Public Relations Officer', contact: '+234 808 000 0008', is_active: true },
];

async function seed() {
  // Clear old sample constitution
  await s.from('constitution').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  console.log('Cleared old constitution data.');

  // Insert full constitution
  const articles = constitutionArticles.map(a => ({
    ...a,
    version: 1,
    is_active: true,
    status: 'approved',
  }));
  const { data: cData, error: cErr } = await s.from('constitution').insert(articles).select('id, title');
  if (cErr) { console.error('Constitution insert error:', cErr.message); return; }
  console.log(`Inserted ${cData.length} constitution articles.`);

  // Insert EXCO members
  const { data: eData, error: eErr } = await s.from('exco_members').insert(excoMembers).select('id, name, position');
  if (eErr) { console.error('EXCO insert error:', eErr.message); return; }
  console.log(`Inserted ${eData.length} EXCO members.`);
  eData.forEach(e => console.log(`  - ${e.position}: ${e.name}`));

  console.log('\nSeed complete!');
}

seed();
